name: Testingabc

on:  push

jobs:
    test-job:
      runs-on: ubuntu-latest

      steps: 
        -name: Hello display
          run: echo "Hello Nagaraju"
        
        -name: display the date
          run: date
