name: testing jobs Based on workflow

on: workflow_dispatch

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: create a one file
        run: echo "Nagaraju welcome to devops" > devops1.txt

      - name: display the content of the file
        run: cat devops1.txt

      - name: display the date
        run: date

      - name: display the present location
        run: pwd
        
